// <auto-generated />
using System;
using CivicConnect.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CivicConnect.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613070524_InitialCreateSQLite")]
    partial class InitialCreateSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GovernmentUnitId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WardCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentUnitId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOfficialResponse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IssueId");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonationCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DonationCategoryId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.DonationCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DonationCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentAmount = 0m,
                            Description = "Quyên góp mua cây xanh, hoa trang trí trồng tại các tuyến ngõ hẻm, công viên công cộng trên địa bàn Phường Bến Nghé.",
                            IsActive = true,
                            Name = "Quỹ Trồng Xanh Đô Thị",
                            TargetAmount = 50000000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentAmount = 0m,
                            Description = "Hỗ trợ lắp đặt hệ thống đèn đường LED thông minh, tiết kiệm điện tại các ngõ hẻm chưa có đủ ánh sáng.",
                            IsActive = true,
                            Name = "Quỹ Thắp Sáng Ngõ Hẻm",
                            TargetAmount = 30000000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentAmount = 0m,
                            Description = "Mua sắm, lắp đặt và sửa chữa các thiết bị vui chơi ngoài trời tại điểm sinh hoạt cộng đồng của phường.",
                            IsActive = true,
                            Name = "Quỹ Nâng Cấp Sân Chơi Trẻ Em",
                            TargetAmount = 100000000m
                        });
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.GovernmentUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WardCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentUnitId");

                    b.ToTable("GovernmentUnits");

                    b.HasData(
                        new
                        {
                            Id = "UBND_Q1",
                            Address = "47 Lê Duẩn, Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                            DistrictCode = "760",
                            Email = "quan1@tphcm.gov.vn",
                            IsActive = true,
                            Name = "UBND Quận 1",
                            Phone = "02838279789",
                            ProvinceCode = "79",
                            Type = 2
                        },
                        new
                        {
                            Id = "UBND_BENNGHE",
                            Address = "29 Nguyễn Trung Ngạn, Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                            DistrictCode = "760",
                            Email = "bennghe.q1@tphcm.gov.vn",
                            IsActive = true,
                            Name = "UBND Phường Bến Nghé",
                            ParentUnitId = "UBND_Q1",
                            Phone = "02838290290",
                            ProvinceCode = "79",
                            Type = 3,
                            WardCode = "26734"
                        },
                        new
                        {
                            Id = "UBND_BIENHOA",
                            Address = "Biên Hòa, Đồng Nai",
                            DistrictCode = "297",
                            Email = "bienhoa@dongnai.gov.vn",
                            IsActive = true,
                            Name = "UBND TP. Biên Hòa",
                            Phone = "02513822501",
                            ProvinceCode = "36",
                            Type = 2
                        },
                        new
                        {
                            Id = "UBND_LONGHUNG",
                            Address = "Long Hưng, Biên Hòa, Đồng Nai",
                            DistrictCode = "297",
                            Email = "longhung.bienhoa@dongnai.gov.vn",
                            IsActive = true,
                            Name = "UBND Phường Long Hưng",
                            ParentUnitId = "UBND_BIENHOA",
                            Phone = "02513822502",
                            ProvinceCode = "36",
                            Type = 3,
                            WardCode = "10834"
                        },
                        new
                        {
                            Id = "UBND_THUDAUMOT",
                            Address = "Thủ Dầu Một, Bình Dương",
                            DistrictCode = "300",
                            Email = "thudaumot@binhduong.gov.vn",
                            IsActive = true,
                            Name = "UBND TP. Thủ Dầu Một",
                            Phone = "02743822001",
                            ProvinceCode = "37",
                            Type = 2
                        },
                        new
                        {
                            Id = "UBND_PHUCUONG",
                            Address = "Phú Cường, Thủ Dầu Một, Bình Dương",
                            DistrictCode = "300",
                            Email = "phucuong.tdm@binhduong.gov.vn",
                            IsActive = true,
                            Name = "UBND Phường Phú Cường",
                            ParentUnitId = "UBND_THUDAUMOT",
                            Phone = "02743822002",
                            ProvinceCode = "37",
                            Type = 3,
                            WardCode = "11000"
                        },
                        new
                        {
                            Id = "UBND_HOANKIEM",
                            Address = "Hoàn Kiếm, Hà Nội",
                            DistrictCode = "001",
                            Email = "hoankiem@hanoi.gov.vn",
                            IsActive = true,
                            Name = "UBND Quận Hoàn Kiếm",
                            Phone = "02438252601",
                            ProvinceCode = "01",
                            Type = 2
                        },
                        new
                        {
                            Id = "UBND_TRANGTIEN",
                            Address = "Tràng Tiền, Hoàn Kiếm, Hà Nội",
                            DistrictCode = "001",
                            Email = "trangtien.hk@hanoi.gov.vn",
                            IsActive = true,
                            Name = "UBND Phường Tràng Tiền",
                            ParentUnitId = "UBND_HOANKIEM",
                            Phone = "02438252602",
                            ProvinceCode = "01",
                            Type = 3,
                            WardCode = "00001"
                        });
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("ParentIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PriorityScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SatisfactionComment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SatisfactionRating")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SeverityScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("AssignedUnitId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentIssueId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.IssueImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueImages");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.IssueStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueStatusHistories");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedIssueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuingUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signer")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Nghị định quy định chi tiết các mức xử phạt đối với cá nhân, tổ chức có hành vi vi phạm vệ sinh môi trường đô thị. Mức phạt tiền tối đa đối với cá nhân là 1.000.000đ cho hành vi vứt rác không đúng nơi quy định, 5.000.000đ cho hành vi tự ý đổ rác thải sinh hoạt ra lòng đường, vỉa hè. Các đơn vị kinh doanh lấn chiếm vỉa hè sẽ bị xử phạt từ 10.000.000đ đến 20.000.000đ và buộc khôi phục tình trạng ban đầu.",
                            DocumentNumber = "45/2026/NĐ-CP",
                            DocumentType = "Nghị định",
                            EffectiveDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Chính phủ ban hành quy định tăng mức phạt đối với các hành vi xả rác bừa bãi, đổ chất thải không đúng nơi quy định và lấn chiếm lòng lề đường.",
                            IsActive = true,
                            IssuingUnit = "Chính phủ",
                            PublishedDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Signer = "Thủ tướng Phạm Minh Chính",
                            SourceUrl = "https://vanban.chinhphu.vn",
                            Tag = "Nghị định",
                            TagClass = "tag-law",
                            Title = "Nghị định 45/2026/NĐ-CP về xử phạt vi phạm hành chính trong lĩnh vực bảo vệ môi trường đô thị"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bộ Xây dựng ban hành Thông tư hướng dẫn chi tiết quy chuẩn kỹ thuật quốc gia về quy hoạch xây dựng. Trong đó, yêu cầu các khu dân cư mới phải đạt tỷ lệ diện tích cây xanh tối thiểu là 2m2/người, khuyến khích các khu dân cư hiện hữu tận dụng các ngõ hẻm để trồng hoa, cây cảnh công cộng và tạo không gian sinh hoạt cộng đồng tự quản.",
                            DocumentNumber = "08/2026/TT-BXD",
                            DocumentType = "Thông tư",
                            EffectiveDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Bộ Xây dựng ban hành hướng dẫn thực hiện các chỉ tiêu về diện tích cây xanh, hoa và hạ tầng tiện ích tại khu dân cư đô thị.",
                            IsActive = true,
                            IssuingUnit = "Bộ Xây dựng",
                            PublishedDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Signer = "Bộ trưởng Nguyễn Thanh Nghị",
                            SourceUrl = "https://moc.gov.vn",
                            Tag = "Thông tư",
                            TagClass = "tag-policy",
                            Title = "Thông tư 08/2026/TT-BXD hướng dẫn về chỉnh trang đô thị và phát triển không gian công cộng xanh"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Nhằm xây dựng nếp sống văn minh đô thị và giữ gìn vệ sinh chung, UBND Phường Bến Nghé phát động chiến dịch ra quân quét dọn các tuyến đường chính và chỉnh trang cây xanh tại ngõ hẻm 45 Lê Thánh Tôn. Kính mời toàn thể nhân dân, các ban ngành đoàn thể và tổ dân phố tham gia đầy đủ. Thời gian bắt đầu từ 7:30 sáng ngày Chủ Nhật.",
                            DocumentNumber = "124/TB-UBND",
                            DocumentType = "Thông báo",
                            EffectiveDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "UBND Phường phát động lễ ra quân tổng vệ sinh, dọn dẹp rác thải và trang trí tuyến hẻm xanh vào sáng Chủ Nhật.",
                            IsActive = true,
                            IssuingUnit = "UBND Phường Bến Nghé",
                            PublishedDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Signer = "Chủ tịch UBND Phường",
                            SourceUrl = "",
                            Tag = "Thông báo",
                            TagClass = "tag-notice",
                            Title = "Thông báo 124/TB-UBND ra quân tổng vệ sinh môi trường trên địa bàn Phường Bến Nghé"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Sáng nay, Quận Đoàn 1 phối hợp với Công ty Môi trường Đô thị tổ chức lễ phát động ra quân làm sạch toàn tuyến kênh chảy qua địa bàn quận. Sau 4 giờ làm việc nỗ lực, lực lượng tình nguyện đã thu gom được hơn 3 tấn rác thải các loại, chủ yếu là túi ni lông, chai nhựa và rác sinh hoạt bị vứt xuống lòng kênh. Đây là hoạt động thường niên nhằm tuyên truyền ý thức bảo vệ môi trường nước cho cư dân xung quanh.",
                            DocumentNumber = "",
                            DocumentType = "Tin tức",
                            EffectiveDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Chiến dịch 'Chung tay bảo vệ dòng sông quê hương' thu hút hàng trăm bạn trẻ dọn dẹp rác thải nhựa và vớt lục bình.",
                            IsActive = true,
                            IssuingUnit = "Quận Đoàn 1",
                            PublishedDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Signer = "",
                            SourceUrl = "https://tuoitre.vn",
                            Tag = "Tin tức",
                            TagClass = "tag-news",
                            Title = "Hơn 500 đoàn viên thanh niên Quận 1 tham gia làm sạch kênh Nhiêu Lộc - Thị Nghè"
                        });
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.UnitCategory", b =>
                {
                    b.Property<string>("GovernmentUnitId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.HasKey("GovernmentUnitId", "Category");

                    b.ToTable("UnitCategories");

                    b.HasData(
                        new
                        {
                            GovernmentUnitId = "UBND_BENNGHE",
                            Category = 1
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_BENNGHE",
                            Category = 2
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_BENNGHE",
                            Category = 3
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_BENNGHE",
                            Category = 4
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_Q1",
                            Category = 1
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_Q1",
                            Category = 2
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_Q1",
                            Category = 3
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_Q1",
                            Category = 4
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_Q1",
                            Category = 5
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_LONGHUNG",
                            Category = 1
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_LONGHUNG",
                            Category = 2
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_LONGHUNG",
                            Category = 3
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_LONGHUNG",
                            Category = 4
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_BIENHOA",
                            Category = 1
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_BIENHOA",
                            Category = 2
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_BIENHOA",
                            Category = 3
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_BIENHOA",
                            Category = 4
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_BIENHOA",
                            Category = 5
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_PHUCUONG",
                            Category = 1
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_PHUCUONG",
                            Category = 2
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_PHUCUONG",
                            Category = 3
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_PHUCUONG",
                            Category = 4
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_THUDAUMOT",
                            Category = 1
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_THUDAUMOT",
                            Category = 2
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_THUDAUMOT",
                            Category = 3
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_THUDAUMOT",
                            Category = 4
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_THUDAUMOT",
                            Category = 5
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_TRANGTIEN",
                            Category = 1
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_TRANGTIEN",
                            Category = 2
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_TRANGTIEN",
                            Category = 3
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_TRANGTIEN",
                            Category = 4
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_HOANKIEM",
                            Category = 1
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_HOANKIEM",
                            Category = 2
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_HOANKIEM",
                            Category = 3
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_HOANKIEM",
                            Category = 4
                        },
                        new
                        {
                            GovernmentUnitId = "UBND_HOANKIEM",
                            Category = 5
                        });
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("UserId", "IssueId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "OfficialProvince",
                            Name = "OfficialProvince",
                            NormalizedName = "OFFICIALPROVINCE"
                        },
                        new
                        {
                            Id = "OfficialDistrict",
                            Name = "OfficialDistrict",
                            NormalizedName = "OFFICIALDISTRICT"
                        },
                        new
                        {
                            Id = "OfficialWard",
                            Name = "OfficialWard",
                            NormalizedName = "OFFICIALWARD"
                        },
                        new
                        {
                            Id = "DepartmentStaff",
                            Name = "DepartmentStaff",
                            NormalizedName = "DEPARTMENTSTAFF"
                        },
                        new
                        {
                            Id = "Citizen",
                            Name = "Citizen",
                            NormalizedName = "CITIZEN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.ApplicationUser", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.GovernmentUnit", "GovernmentUnit")
                        .WithMany("Officials")
                        .HasForeignKey("GovernmentUnitId");

                    b.Navigation("GovernmentUnit");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Comment", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicConnect.Web.Models.Entities.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicConnect.Web.Models.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Issue");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Donation", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.DonationCategory", "DonationCategory")
                        .WithMany("Donations")
                        .HasForeignKey("DonationCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonationCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.GovernmentUnit", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.GovernmentUnit", "ParentUnit")
                        .WithMany("ChildUnits")
                        .HasForeignKey("ParentUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentUnit");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Issue", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CivicConnect.Web.Models.Entities.GovernmentUnit", "AssignedUnit")
                        .WithMany("AssignedIssues")
                        .HasForeignKey("AssignedUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", "Author")
                        .WithMany("Issues")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicConnect.Web.Models.Entities.Issue", "ParentIssue")
                        .WithMany("ChildIssues")
                        .HasForeignKey("ParentIssueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedTo");

                    b.Navigation("AssignedUnit");

                    b.Navigation("Author");

                    b.Navigation("ParentIssue");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.IssueImage", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.Issue", "Issue")
                        .WithMany("Images")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.IssueStatusHistory", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivicConnect.Web.Models.Entities.Issue", "Issue")
                        .WithMany("StatusHistory")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.UnitCategory", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.GovernmentUnit", "GovernmentUnit")
                        .WithMany("Categories")
                        .HasForeignKey("GovernmentUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovernmentUnit");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Vote", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.Issue", null)
                        .WithMany("Votes")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", null)
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CivicConnect.Web.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Issues");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.DonationCategory", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.GovernmentUnit", b =>
                {
                    b.Navigation("AssignedIssues");

                    b.Navigation("Categories");

                    b.Navigation("ChildUnits");

                    b.Navigation("Officials");
                });

            modelBuilder.Entity("CivicConnect.Web.Models.Entities.Issue", b =>
                {
                    b.Navigation("ChildIssues");

                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("StatusHistory");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
